### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by ro-ka** [S1SYPHOS/kirby3-highlight#1]
I want to use this plugin and moved the downloaded folder to the plugins folder. But the layout (the DOM) of articles is totally broken then. I used kirby-highlight in Kirby 2 with the same content without problems.

-----

This is the page before: 
![Bildschirmfoto vom 2019-06-13 um 22 31 29](https://user-images.githubusercontent.com/840022/59465515-5e662080-8e2b-11e9-9001-daf8ac8ef88d.png)

-----

This is the page with the plugin activated:
![Bildschirmfoto vom 2019-06-13 um 22 31 43](https://user-images.githubusercontent.com/840022/59465551-7342b400-8e2b-11e9-9943-5801b93b57a7.png)

-----

As you can see in the DOM, the `<h2>` is wrapping around the whole block, including all the other subelements. But classes for the code block is still missing completely:
![Bildschirmfoto 2019-06-13 um 22 33 43](https://user-images.githubusercontent.com/840022/59465747-de8c8600-8e2b-11e9-83e7-874b76abfcf2.png)

-----

Any ideas on why this happens?

**Comment by ro-ka** [comment]
I just found the Troubleshooting section in the Readme, but the linked document doesn’t exist anymore. Cannot find another list in the repo. May this be a problem?

Also I figured out that some pages on my site don’t work at all when the plugin is included. See the error beneath:
![Bildschirmfoto vom 2019-06-13 um 22 52 00](https://user-images.githubusercontent.com/840022/59466560-e2b9a300-8e2d-11e9-8b39-595e0a8f8e2f.png)

**Comment by johannschopplich** [comment]
@ro-ka I've had the same problems and decided to fork and overhaul this package. Tests are included as well.

👉 https://github.com/johannschopplich/kirby-highlighter

**Comment by ro-ka** [comment]
Nice, thanks!

**Comment by johannschopplich** [comment]
@ro-ka Glad to hear! Please let me know if anything doesn't work and create an issue over at my repository. 🙂

**Comment by ro-ka** [comment]
Already did so.  😜
