### ISSUE TITLE
Does not work with umlauts ö,ä,ü,ß

### ISSUE THREAD

**Issue by frankgerhardt** [S1SYPHOS/kirby3-highlight#2]
Installed as submodule, umlauts get transformed into funny characters instead of being left alone.

Sorry for the short bug report, better than nothing.

**Comment by johannschopplich** [comment]
@frankgerhardt I've created an overhaul of this package. Tests for umlauts are included as well.

👉 https://github.com/johannschopplich/kirby-highlighter
