### ISSUE TITLE
DOMDocument::loadHTML(): Tag figure invalid in Entity

### ISSUE THREAD

**Issue by benoitwimart** [S1SYPHOS/kirby3-highlight#3]
Hi,

I have this error   `DOMDocument::loadHTML(): Tag figure invalid in Entity`, when I put an image in my text.
This line fixes the problem.
`            // Converting kirbytext to an HTML document
            // See https://secure.php.net/manual/en/class.domdocument.php
            $html = new DOMDocument();
            libxml_use_internal_errors(true); // <---- `

**Comment by johannschopplich** [comment]
@benoitwimart To silence errors I've created a fork and overhauled this package. Tests are included as well.

👉 https://github.com/johannschopplich/kirby-highlighter

**Comment by benoitwimart** [comment]
OK, I will try :)

**Comment by johannschopplich** [comment]
@benoitwimart Thanks! Please let me know if anything doesn't work as expected.
